### ISSUE TITLE
Hi HenryJia, Can I have the VGG19 model you use in the project??

### ISSUE THREAD

**Issue by ziruiLiu-g** [HenryJia/pytorch-deep-painterly-harmonization#2]
Because I am trying to learn about the deep painterly harmonization project through your project. And I would really appreaciate if  you can upload your VGG_ILSVRC_19_layers.pytorch.

And the model will be just used for learning, not for commercial purposes

**Comment by HenryJia** [comment]
Hi 

Sorry for the late reply, I've been away for a while, it's c onverted from the Oxford VGG19 caffe model, it's identical, but in pytorch's format

http://www.robots.ox.ac.uk/~vgg/research/very_deep/

I used this repo to do the conversion

https://github.com/lichengunc/pytorch-vgg/

Thanks

Hengjian (Henry) Jia
